#!/usr/bin/env python2.7
import math
from sys import *

if len(argv) != 8:
    quit(84)
    
i = 1
while i != 8:
    if argv[i][0] == '-':
        if str.isdigit(argv[i][1:]) == False:
            quit(84)
        elif argv[i].replace('.','', 1).isdigit() == False:
            quit(84)
    i += 1

x1 = float(argv[1])
y1 = float(argv[2])
z1 = float(argv[3])
x = float(argv[4])
y = float(argv[5])
z = float(argv[6])
nb = float(argv[7])

sx = x - x1
sy = y - y1
sz = z - z1
print "The speed vector coordinate are :\n({:.2f};{:.2f};{:.2f})".format(sx, sy, sz)

ex = x + sx * nb
ey = y + sy * nb
ez = z + sz * nb
print "At time t+{:.0f}, ball coordinates will be :\n({:.2f};{:.2f};{:.2f})".format(nb, ex, ey, ez)

if z >= 0 and ez <= 0:
    ns = math.sqrt(math.pow(sx, 2) + math.pow(sy, 2) + math.pow(sz, 2))
    nz = math.sqrt(math.pow(sz, 2))
    sv = math.asin(nz / ns)
    sv = math.degrees(sv)
    print "The incidence angle is :\n{:.2f} degrees".format(sv)
elif z <= 0 and ez >= 0:
    ns = math.sqrt(math.pow(sx, 2) + math.pow(sy, 2) + math.pow(sz, 2))
    nz = math.sqrt(math.pow(sz, 2))
    sv = math.asin(nz / ns)
    sv = math.degrees(sv)
    print "The incidence angle is :\n{:.2f} degrees".format(sv)
else:
    print "The ball won't reach the bat."
